version: "3.8"

services:
  pkr-postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PKR_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "${PKR_PGDATA_DIR}:/var/lib/postgresql/data"
      - "${PKR_PGCONF_DIR}/postgresql.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"

  pkr-redis:
    image: redis:2.8
    restart: unless-stopped
    ports:
      - "6379:6379"

  pkr-backend-api:
    build: .
    environment: *pkr-backend-variables
    command: uwsgi --ini /etc/uwsgi.ini
    ports:
      - "8001:8001"
    depends_on:
      - pkr-postgres
      - pkr-redis
    volumes:
      - ".:/code"

  pkr-backend-ws:
    build: .
    environment: *pkr-backend-variables
    command: daphne -e ssl:8002:privateKey=${PKR_LETSENCRYPT_DIR}/live/${PKR_DOMAIN}/privkey.pem:certKey=${PKR_LETSENCRYPT_DIR}/live/${PKR_DOMAIN}/cert.pem pkrbcknd.asgi:application
    ports:
      - "8002:8002"
    depends_on:
      - pkr-postgres
      - pkr-redis
    volumes:
      - ".:/code"
      - ${PKR_LETSENCRYPT_DIR}:${PKR_LETSENCRYPT_DIR}

  pkr-makemigrations-game:
    build: .
    environment: *pkr-backend-variables
    command: python manage.py makemigrations game
    depends_on:
      - pkr-postgres
    volumes:
      - ".:/code"

  pkr-migrate:
    build: .
    environment: *pkr-backend-variables
    command: python manage.py migrate
    depends_on:
      - pkr-postgres
    volumes:
      - ".:/code"

  pkr-createsuperuser:
    build: .
    environment: *pkr-backend-variables
    stdin_open: true
    tty: true
    command: python manage.py createsuperuser
    depends_on:
      - pkr-postgres
    volumes:
      - ".:/code"

  pkr-front:
    build: ./front
    restart: unless-stopped
    ports:
      - 443:443/tcp
    volumes:
      - ${PKR_LETSENCRYPT_DIR}:${PKR_LETSENCRYPT_DIR}
