version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./deploy/postgres/data:/var/lib/postgresql/data
      - ./deploy/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:2.8
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    command: uwsgi --ini /etc/uwsgi.ini
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
      - ./deploy/uwsgi.ini:/etc/uwsgi.ini:ro

  daphne:
    build: .
    command: daphne -e ssl:8002:privateKey=/certs/live/${DOMAIN}/privkey.pem:certKey=/certs/live/${DOMAIN}/cert.pem pkrbcknd.asgi:application
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
      - ./deploy/certbot/conf/:/certs:ro

  front:
    build: ./front
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - ./deploy/certbot/www:/var/www/certbot/:ro
      - ./deploy/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./deploy/certbot/www/:/var/www/certbot/:rw
      - ./deploy/certbot/conf/:/etc/letsencrypt/:rw
