version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./deploy/postgres/data:/var/lib/postgresql/data
      - ./deploy/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10
    restart: unless-stopped
    ports:
      - "5672:5672"

  app:
    build:
      context: .
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    command: uwsgi --ini /etc/uwsgi.ini
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - .:/code
      - ./deploy/uwsgi.ini:/etc/uwsgi.ini:ro
      - ./deploy/static:/code/static

  celery:
    build:
      context: .
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    command: celery -A pkrbcknd worker --beat -l INFO
    env_file: .env
    volumes:
      - .:/code
      - ./deploy/uwsgi.ini:/etc/uwsgi.ini:ro
      - ./deploy/static:/code/static

  front:
    build: ./front
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - ./deploy/certbot/www:/var/www/certbot/:ro
      - ./deploy/certbot/conf/:/etc/nginx/ssl/:ro
      - ./deploy/static:/app/static:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./deploy/certbot/www/:/var/www/certbot/:rw
      - ./deploy/certbot/conf/:/etc/letsencrypt/:rw
