# Generated by Django 3.2 on 2022-07-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('C2', '2 of clubs'), ('C3', '3 of clubs'), ('C4', '4 of clubs'), ('C5', '5 of clubs'), ('C6', '6 of clubs'), ('C7', '7 of clubs'), ('C8', '8 of clubs'), ('C9', '9 of clubs'), ('CX', '10 of clubs'), ('CJ', 'J of clubs'), ('CQ', 'Q of clubs'), ('CK', 'K of clubs'), ('CA', 'A of clubs'), ('D2', '2 of diamonds'), ('D3', '3 of diamonds'), ('D4', '4 of diamonds'), ('D5', '5 of diamonds'), ('D6', '6 of diamonds'), ('D7', '7 of diamonds'), ('D8', '8 of diamonds'), ('D9', '9 of diamonds'), ('DX', '10 of diamonds'), ('DJ', 'J of diamonds'), ('DQ', 'Q of diamonds'), ('DK', 'K of diamonds'), ('DA', 'A of diamonds'), ('H2', '2 of hearts'), ('H3', '3 of hearts'), ('H4', '4 of hearts'), ('H5', '5 of hearts'), ('H6', '6 of hearts'), ('H7', '7 of hearts'), ('H8', '8 of hearts'), ('H9', '9 of hearts'), ('HX', '10 of hearts'), ('HJ', 'J of hearts'), ('HQ', 'Q of hearts'), ('HK', 'K of hearts'), ('HA', 'A of hearts'), ('S2', '2 of spades'), ('S3', '3 of spades'), ('S4', '4 of spades'), ('S5', '5 of spades'), ('S6', '6 of spades'), ('S7', '7 of spades'), ('S8', '8 of spades'), ('S9', '9 of spades'), ('SX', '10 of spades'), ('SH', 'J of shearts'), ('SQ', 'Q of spades'), ('SK', 'K of spades'), ('SA', 'A of spades')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('ante', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('wt', 'waiting for players'), ('pf', 'preflop'), ('fp', 'flop'), ('tn', 'turn'), ('rv', 'river'), ('no', 'idle')], default='no', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTableCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(default=0)),
                ('raise_value', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('bet', 'bet'), ('call', 'call'), ('raise', 'raise'), ('check', 'check'), ('fold', 'fold')], default='fold', max_length=5)),
                ('role', models.CharField(choices=[('s', 'small blind'), ('b', 'big blind'), ('d', 'default')], default='d', max_length=1)),
                ('hand', models.ManyToManyField(to='game.Card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='deck',
            field=models.ManyToManyField(related_name='_game_room_deck_+', through='game.RoomDeckCard', to='game.Card'),
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='_game_room_players_+', through='game.RoomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='table',
            field=models.ManyToManyField(related_name='_game_room_table_+', through='game.RoomTableCard', to='game.Card'),
        ),
    ]
