# Generated by Django 3.2.14 on 2022-07-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=200, verbose_name='room url')),
                ('name', models.CharField(default='', max_length=200, verbose_name='room name')),
                ('state', models.JSONField(null=True, verbose_name='current state')),
                ('bank', models.PositiveIntegerField(default=0, verbose_name='current bank')),
                ('deck', models.JSONField(null=True, verbose_name='current deck')),
                ('table', models.JSONField(null=True, verbose_name='current table')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='player name')),
                ('decision', models.JSONField(null=True, verbose_name='current decision')),
                ('hand', models.JSONField(null=True, verbose_name='current hand')),
                ('wallet', models.PositiveIntegerField(default=0, verbose_name='current wallet')),
                ('ready', models.BooleanField(default=False, verbose_name='is player ready')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
    ]
